name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
      - name: Run ESLint
        run: npm run lint-build
      - name: Run Stylelint
        run: npm run stylelint
      - name: Run tests
        run: npm run test-build
      - uses: codecov/codecov-action@v3
